'use strict';
const PEOPLE=['JaK','JaV','MoK','MaU','MiD','Bě','Iv','MaK'];
const form=document.querySelector('#vote-form'), statusBox=document.querySelector('#status');
const endpoint=window.VOTE_CONFIG?.endpoint||'';
let person='', rows=[], busy=false;
function currentVotes(){return Object.fromEntries(rows.map(r=>[String(r.number),Number(form.elements['v'+r.number]?.value)||null]));}
function update(){const votes=currentVotes(),count=Object.values(votes).filter(Boolean).length;document.querySelector('#progress').textContent=count+' / '+rows.length;document.querySelector('#submit').disabled=busy||!person||count!==rows.length||!endpoint;rows.forEach(r=>document.querySelector('#row'+r.number).classList.toggle('voted',Boolean(votes[r.number])));if(!busy)statusBox.textContent=person?`${person} · ${count} z ${rows.length} míst vyplněno.`:'Vyber iniciály a ohodnoť všech 16 míst.';}
async function start(){try{const res=await fetch('assets/lokality.json');if(!res.ok)throw Error();rows=await res.json();await renderMap();document.querySelector('#names').innerHTML=PEOPLE.map(p=>`<label class="person"><input type="radio" name="person" value="${p}" required><span>${p}</span></label>`).join('');document.querySelector('#destinations').innerHTML=rows.map(r=>`<tr id="row${r.number}"><td><div class="destination"><div><strong>${r.number}. ${r.region} – ${r.peak}</strong><small>${r.height} m n. m.</small></div></div></td><td class="travel" data-city="Praha">${r.pr||"?"}</td><td class="travel" data-city="Brno">${r.br||"?"}</td>${[1,2,3,4,5].map(g=>`<td><label class="grade"><input type="radio" name="v${r.number}" value="${g}" required aria-label="${r.peak}: ${g}"><span>${g}</span></label></td>`).join('')}</tr>`).join('');const noteLabel=document.createElement('label');noteLabel.className='notes';noteLabel.innerHTML='<span>Poznámka <small>(nepovinné)</small></span><textarea id="notes" maxlength="1000" placeholder="Cokoli – myšlenka, která nemá do příštího roku zapadnout"></textarea>';document.querySelector('.people').before(noteLabel);document.querySelector('#connection').textContent=endpoint?'':'Náhled stránky: společné odesílání hlasů ještě není připojené. Volby si můžeš vyzkoušet.';form.addEventListener('change',e=>{if(e.target.name==='person'){person=e.target.value;}update()});update()}catch{statusBox.textContent='Seznam míst se nepodařilo načíst. Obnov stránku.'}}
form.addEventListener('submit',async e=>{e.preventDefault();if(busy||!endpoint||!form.reportValidity())return;const selected=person,votes=currentVotes();if(!PEOPLE.includes(selected)||Object.values(votes).some(v=>!Number.isInteger(v)||v<1||v>5))return;busy=true;update();form.querySelectorAll('input').forEach(e=>e.disabled=true);statusBox.textContent='Ukládám tvoje hlasování…';const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),20000);try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({person:selected,votes,notes:document.querySelector('#notes')?.value.trim()||''}),signal:controller.signal});if(!response.ok)throw Error();const data=await response.json();if(data.ok!==true||data.person!==selected)throw Error();form.reset();person='';try{localStorage.removeItem('dj2027-current');PEOPLE.forEach(p=>localStorage.removeItem('dj2027-'+p));}catch{}update();statusBox.textContent=`Hotovo, ${selected}! Tvoje hlasování je uložené. Můžeš vyplnit nové hlasování.`}catch{statusBox.textContent='Uložení se nepodařilo potvrdit. Výběr zůstal ve formuláři; zkus odeslání znovu.'}finally{clearTimeout(timeout);busy=false;form.querySelectorAll('input').forEach(e=>e.disabled=false);document.querySelector('#submit').disabled=!endpoint||!person||Object.values(currentVotes()).some(v=>!v)}});
async function renderMap(){
  const label=r=>`${r.number}. ${r.region} – ${r.peak}`;
  document.querySelector('#map-list').innerHTML=rows.map(r=>`<li><a href="#row${r.number}">${label(r)} <small>· ${r.height} m</small></a></li>`).join('');
  document.querySelector('#sources').innerHTML=rows.map(r=>`<li><a href="${r.extra||r.src}" target="_blank" rel="noopener">${label(r)} · ${r.height} m</a>${r.note?' — '+r.note:''}</li>`).join('');
  try{
    const response=await fetch('assets/map-outline.json');if(!response.ok)throw Error();const outline=await response.json();
    const pins=rows.map(r=>{const x=(r.lon-12)*105+20,y=(51.2-r.lat)*163+10,dy=r.number===11?-12:r.number===12?12:0;
      return `${dy?`<path class="leader" d="M${x} ${y} L${x} ${y+dy}"/>`:''}<a class="pin" href="#row${r.number}" aria-label="${label(r)}, ${r.height} metrů, přejít k hodnocení"><title>${label(r)} · ${r.height} m</title><circle cx="${x}" cy="${y+dy}" r="14"/><text x="${x}" y="${y+dy}">${r.number}</text></a>`;}).join('');
    document.querySelector('#map').innerHTML=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 750 470" role="group" aria-label="Mapa Česka s odkazy na 16 lokalit"><path class="country" d="${outline.path}"/>${pins}</svg>`;
  }catch{document.querySelector('#map').textContent='Mapa se nepodařila načíst. Vyber lokalitu ze seznamu vedle.';}
}
start();
