'use strict';
const PEOPLE=['JaK','JaV','MoK','MaU','MiD','Bě','Iv','MaK'];
const form=document.querySelector('#vote-form'), statusBox=document.querySelector('#status');
const endpoint=window.VOTE_CONFIG?.endpoint||'';
let person='', rows=[], busy=false;
const drafts=new Map();
function storageGet(key){try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return {}}}
function currentVotes(){return Object.fromEntries(rows.map(r=>[String(r.number),Number(form.elements['v'+r.number]?.value)||null]));}
function update(){const votes=currentVotes(),count=Object.values(votes).filter(Boolean).length;document.querySelector('#progress').textContent=count+' / '+rows.length;document.querySelector('#submit').disabled=busy||!person||count!==rows.length||!endpoint;rows.forEach(r=>document.querySelector('#row'+r.number).classList.toggle('voted',Boolean(votes[r.number])));if(person){drafts.set(person,votes);try{localStorage.setItem('dj2027-'+person,JSON.stringify(votes))}catch{}}if(!busy)statusBox.textContent=person?`${person} · ${count} z ${rows.length} míst vyplněno. Rozpracovaný výběr zůstává v tomto prohlížeči.`:'Vyber iniciály a ohodnoť všech 16 míst.';}
async function start(){try{const res=await fetch('assets/lokality.json');if(!res.ok)throw Error();rows=await res.json();document.querySelector('#names').innerHTML=PEOPLE.map(p=>`<label class="person"><input type="radio" name="person" value="${p}" required><span>${p}</span></label>`).join('');document.querySelector('#destinations').innerHTML=rows.map(r=>`<tr id="row${r.number}"><td><div class="destination"><span class="number">${r.number}</span><div><strong>${r.peak}</strong><small>${r.region}</small></div></div></td><td class="travel">${r.pr||"?"}</td><td class="travel">${r.br||"?"}</td>${[1,2,3,4,5].map(g=>`<td><label class="grade"><input type="radio" name="v${r.number}" value="${g}" required aria-label="${r.peak}: ${g}"><span>${g}</span></label></td>`).join('')}</tr>`).join('');const noteLabel=document.createElement('label');noteLabel.className='notes';noteLabel.innerHTML='<span>Poznámka <small>(nepovinné)</small></span><textarea id="notes" maxlength="1000" placeholder="Např. co ověřit nebo jakou chalupu hledat…"></textarea>';document.querySelector('.submit-bar').before(noteLabel);document.querySelector('#connection').textContent=endpoint?'':'Náhled stránky: společné odesílání hlasů ještě není připojené. Volby si můžeš vyzkoušet.';form.addEventListener('change',e=>{if(e.target.name==='person'){person=e.target.value;const saved=drafts.get(person)||storageGet('dj2027-'+person);rows.forEach(r=>{for(const el of form.querySelectorAll(`[name="v${r.number}"]`))el.checked=Number(el.value)===saved[r.number]})}update()});update()}catch{statusBox.textContent='Seznam míst se nepodařilo načíst. Obnov stránku.'}}
form.addEventListener('submit',async e=>{e.preventDefault();if(busy||!endpoint||!form.reportValidity())return;const selected=person,votes=currentVotes();if(!PEOPLE.includes(selected)||Object.values(votes).some(v=>!Number.isInteger(v)||v<1||v>5))return;busy=true;update();form.querySelectorAll('input').forEach(e=>e.disabled=true);statusBox.textContent='Ukládám tvoje hlasování…';const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),20000);try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({person:selected,votes,notes:document.querySelector('#notes')?.value.trim()||''}),signal:controller.signal});if(!response.ok)throw Error();const data=await response.json();if(data.ok!==true||data.person!==selected)throw Error();statusBox.textContent=`Hotovo, ${selected}! Tvoje hlasování je uložené. Další odeslání ho aktualizuje.`}catch{statusBox.textContent='Uložení se nepodařilo potvrdit. Výběr zůstal v prohlížeči; zkus odeslání znovu.'}finally{clearTimeout(timeout);busy=false;form.querySelectorAll('input').forEach(e=>e.disabled=false);document.querySelector('#submit').disabled=!endpoint}});
start();
